on: push
name: test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get

      - name: run tests
        uses: steebchen/flutter@v1.1.0
        with:
          args: test
